name: matzo
description: To do Listen fÃ¼r Kategorien erstellen
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.1
  
  # Lokale Datenbank
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.8.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Biometric Authentication
  local_auth: ^2.2.0
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # UI
  flutter_slidable: ^3.0.0
  reorderable_grid_view: ^2.2.8
  confetti: ^0.7.0
  
  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  
  # Testing & Mocking
  mockito: ^5.4.4
  build_runner: ^2.4.6
  bloc_test: ^9.1.5

  # Code Coverage
  coverage: ^1.7.0

flutter:
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Matzo.png"  # Pfad zu deinem App-Icon